import { DAY_LABEL, NOTIFICATION_TYPE, type Notification } from "./types";

const AVATARS = [
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&h=80&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=80&h=80&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=80&h=80&fit=crop&crop=face",
] as const;

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    type: NOTIFICATION_TYPE.REMINDER,
    title: "Maria Silva enviou um lembrete",
    avatar: AVATARS[0],
    unread: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.TODAY,
    archived: false,
  },
  {
    id: "2",
    type: NOTIFICATION_TYPE.STATUS_CHANGED,
    title: "Carlos Mendes alterou o status de uma tarefa",
    avatar: AVATARS[1],
    unread: true,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.TODAY,
    archived: false,
    previousStatus: "Em andamento",
    currentStatus: "Concluído",
  },
  {
    id: "3",
    type: NOTIFICATION_TYPE.COMMENT,
    title: "Ana Paula comentou em uma tarefa",
    avatar: AVATARS[2],
    unread: true,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.TODAY,
    archived: false,
    comment:
      "Onde posso encontrar o processo de onboarding para novos pacientes?",
  },
  {
    id: "4",
    type: NOTIFICATION_TYPE.REMINDER,
    title: "Pedro Santos enviou um lembrete",
    avatar: AVATARS[3],
    unread: true,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.TODAY,
    archived: false,
  },
  {
    id: "5",
    type: NOTIFICATION_TYPE.COMMENT,
    title: "Juliana Costa mencionou você em um comentário",
    avatar: AVATARS[4],
    unread: true,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.TODAY,
    archived: false,
    comment:
      "@você poderia revisar o relatório antes do envio para o convênio?",
  },
  {
    id: "6",
    type: NOTIFICATION_TYPE.STATUS_CHANGED,
    title: "Rafael Oliveira alterou o status de uma tarefa",
    avatar: AVATARS[5],
    unread: false,
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.YESTERDAY,
    archived: false,
    previousStatus: "Em andamento",
    currentStatus: "Concluído",
  },
  {
    id: "7",
    type: NOTIFICATION_TYPE.REMINDER,
    title: "Fernanda Lima enviou um lembrete",
    avatar: AVATARS[6],
    unread: false,
    createdAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.YESTERDAY,
    archived: false,
  },
  {
    id: "8",
    type: NOTIFICATION_TYPE.COMMENT,
    title: "Lucas Ferreira comentou em uma tarefa",
    avatar: AVATARS[7],
    unread: false,
    createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.YESTERDAY,
    archived: false,
    comment: "Documentação atualizada. Pode seguir com a implementação.",
  },
  {
    id: "9",
    type: NOTIFICATION_TYPE.STATUS_CHANGED,
    title: "Beatriz Alves alterou o status de uma tarefa",
    avatar: AVATARS[0],
    unread: false,
    createdAt: new Date(Date.now() - 32 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.YESTERDAY,
    archived: false,
    previousStatus: "Em andamento",
    currentStatus: "Concluído",
  },
  {
    id: "10",
    type: NOTIFICATION_TYPE.REMINDER,
    title: "Gabriel Souza respondeu ao seu lembrete",
    avatar: AVATARS[1],
    unread: false,
    createdAt: new Date(Date.now() - 34 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.YESTERDAY,
    archived: false,
  },
  {
    id: "11",
    type: NOTIFICATION_TYPE.COMMENT,
    title: "Camila Rocha comentou em uma tarefa",
    avatar: AVATARS[2],
    unread: false,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.YESTERDAY,
    archived: false,
    comment: "Precisamos alinhar a agenda da próxima semana com a recepção.",
  },
  {
    id: "12",
    type: NOTIFICATION_TYPE.STATUS_CHANGED,
    title: "Thiago Martins alterou o status de uma tarefa",
    avatar: AVATARS[3],
    unread: false,
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.MONDAY,
    archived: false,
    previousStatus: "Em andamento",
    currentStatus: "Concluído",
  },
  {
    id: "13",
    type: NOTIFICATION_TYPE.REMINDER,
    title: "Patricia Gomes enviou um lembrete",
    avatar: AVATARS[4],
    unread: false,
    createdAt: new Date(Date.now() - 74 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.MONDAY,
    archived: false,
  },
  {
    id: "14",
    type: NOTIFICATION_TYPE.COMMENT,
    title: "Rodrigo Nunes comentou em uma tarefa",
    avatar: AVATARS[5],
    unread: false,
    createdAt: new Date(Date.now() - 76 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.MONDAY,
    archived: true,
    comment: "Arquivo enviado por e-mail. Confirme o recebimento, por favor.",
  },
  {
    id: "15",
    type: NOTIFICATION_TYPE.STATUS_CHANGED,
    title: "Mariana Dias atualizou o prazo de uma tarefa",
    avatar: AVATARS[6],
    unread: false,
    createdAt: new Date(Date.now() - 78 * 60 * 60 * 1000).toISOString(),
    dayLabel: DAY_LABEL.MONDAY,
    archived: true,
    previousStatus: "Em andamento",
    currentStatus: "Concluído",
  },
];
